# Generated by Django 4.0.6 on 2022-08-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
